export const portfolios = [
  {
    id: 1,
    name: "FINMASTER APP",
    url: "https://veegil-media-test.netlify.app",
    desc: "FinMaster is a cutting-edge fintech bank app that empowers you to take control of your finances like never before. With its robust features and user-friendly interface, FinMaster provides a seamless banking experience right at your fingertips. From managing your accounts and budgeting to making secure transactions, FinMaster is your ultimate financial companion.",
    img: "/bankapp.png",
  },
  {
    id: 2,
    name: "SALEPRO APP",
    url: "https://joniedev-pos.netlify.app/",
    desc: "SalePro is a versatile point of sale (POS) app designed to streamline your business operations and enhance customer experiences. With its intuitive interface and powerful features, SalePro revolutionizes the way you manage sales, inventory, and payments. Whether you run a retail store, restaurant, or any other business, SalePro is your all-in-one solution for efficient and seamless transactions.",
    img: "/posapp.png",
  },
  {
    id: 3,
    name: "SHOPSOLO APP",
    url: "https://vanillajs-ecommerce-app.netlify.app/",
    desc: "ShopSolo is a dedicated single-brand e-commerce app that brings the entire collection of brand products right to your fingertips. Designed for seamless shopping experiences, ShopSolo offers a wide range of products from brand products and provides a convenient platform to explore, purchase, and stay updated on the latest offerings. Whether you're a fashion enthusiast, tech lover, or fan of brand products, ShopSolo is your go-to app for exclusive shopping",
    img: "/ecommerceapp.png",
  },
  {
    id: 4,
    name: "FILTEREASY APP",
    url: "https://advanced-filtering.netlify.app/",
    desc: "FilterEasy is a powerful React-based product filtering app that simplifies the process of finding the perfect products tailored to your preferences. With its intuitive interface and robust filtering capabilities, FilterEasy allows you to effortlessly narrow down your search and discover products that meet your specific criteria.",
    img: "/adfilterapp.png",
  },
  {
    id: 5,
    name: "MERN SOCIAL APP",
    url: "/",
    desc: "Devdomain is a platform that connects users mostly developers. It is a platform where one can share ideas and market ones skills and get connected to clients. Users have to create profile and follow one another for wider connection. Users can also create, like/unlike,update, and delete posts as well as comment,like/unlike,update,delete comments and replies.",
    img: "/featured.jpeg",
  },
  {
    id: 6,
    name: "SHOP ARENA",
    url: "/",
    desc: "Shop Arena is a user-friendly and feature-rich e-commerce app that revolutionizes the way people shop online. With a sleek and intuitive interface, Shop Arena offers a seamless shopping experience right at your fingertips. Whether you're looking for fashion, electronics, home decor, or any other products, Shop Arena has you covered with its vast catalog of items from trusted sellers. It also has PayPal payment system implementation",
    img: "/ecommercepage.png",
  },

  {
    id: 7,
    name: "BLOG APP",
    url: "/",
    desc: "This is a blog app that dishes out latest news to the site visitors. It is full of contents grouped in categories viz:sports,entertainment,music,food,culture,lifestyle,family,religion,technology,business,career,politics,education,investment and lot more. Users can create,comment,edit and delete posts.",
    img: "/blogpage.png",
  },
  {
    id: 8,
    name: "SHARE GROWTH",
    url: "https://sharegrowth.ng",
    desc: "We have partnered with over 200 trusted providers across Nigeria to give you access to everything you need to start or scale - without the usual headache. You do not have to break the bank to grow. You just need the right partner. Get started today. Your business won’t wait. And now, you don’t have to either.",
    img: "/sharegrowthapp.png",
  },
  {
    id: 9,
    name: "TECHBRAVERY",
    url: "https://techbravery.netlify.app/",
    desc: "Unlock the true potential of your online presence with our premier web development agency. At Techbravery Software Solutions, we pride ourselves on delivering stunning secure and responsive websites that captivate audiences, drive conversions, and elevate your brand to new heights. With our expert team of developers, designers, and digital strategists, we are committed to crafting tailor-made solutions that exceed your expectations.",
    img: "/techbraveryapp.png",
  },
  {
    id: 10,
    name: "ANNUNAKI NODE",
    url: "https://testadnnode.netlify.app/",
    desc: "Unlock the true potential of your online presence with our premier web development agency. At Techbravery Software Solutions, we pride ourselves on delivering stunning secure and responsive websites that captivate audiences, drive conversions, and elevate your brand to new heights. With our expert team of developers, designers, and digital strategists, we are committed to crafting tailor-made solutions that exceed your expectations.",
    img: "/anodeapp.png",
  },
  {
    id: 10,
    name: "PORTFOLIO",
    url: "https://joniedev1.netlify.app/",
    desc: "Unlock the true potential of your online presence with our premier web development agency. At Techbravery Software Solutions, we pride ourselves on delivering stunning secure and responsive websites that captivate audiences, drive conversions, and elevate your brand to new heights. With our expert team of developers, designers, and digital strategists, we are committed to crafting tailor-made solutions that exceed your expectations.",
    img: "/portfolioapp.png",
  },
];
