export const features = [
  {
    id: 1,
    title: "Feature One",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic laudantium possimus sit nam ipsam dicta nisi magni fuga placeat voluptate quam, ullam quo culpa, velit ipsa, eligendi amet est. Deserunt!",
    url: "url",
    img: "/assets/img11.jpg",
    category: "Web, iOS & Android App",
  },
  {
    id: 2,
    title: "Feature Two",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic laudantium possimus sit nam ipsam dicta nisi magni fuga placeat voluptate quam, ullam quo culpa, velit ipsa, eligendi amet est. Deserunt!",
    url: "url",
    img: "/assets/img2.jpg",
    category: "Web App",
  },
  {
    id: 3,
    title: "Feature Three",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic laudantium possimus sit nam ipsam dicta nisi magni fuga placeat voluptate quam, ullam quo culpa, velit ipsa, eligendi amet est. Deserunt!",
    url: "url",
    img: "/assets/screen4.jpg",
    category: "Android App",
  },
  {
    id: 4,
    title: "Feature Four",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic laudantium possimus sit nam ipsam dicta nisi magni fuga placeat voluptate quam, ullam quo culpa, velit ipsa, eligendi amet est. Deserunt!",
    url: "url",
    img: "/assets/img5.jpg",
    category: "iOS App",
  },
  {
    id: 5,
    title: "Feature Five",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic laudantium possimus sit nam ipsam dicta nisi magni fuga placeat voluptate quam, ullam quo culpa, velit ipsa, eligendi amet est. Deserunt!",
    url: "url",
    img: "/assets/img8.jpg",
    category: "Desktop App",
  },
  {
    id: 6,
    title: "Feature Six",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic laudantium possimus sit nam ipsam dicta nisi magni fuga placeat voluptate quam, ullam quo culpa, velit ipsa, eligendi amet est. Deserunt!",
    url: "url",
    img: "/assets/img11.jpg",
    category: "Web, iOS & Android App",
  },
  {
    id: 7,
    title: "Feature One",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic laudantium possimus sit nam ipsam dicta nisi magni fuga placeat voluptate quam, ullam quo culpa, velit ipsa, eligendi amet est. Deserunt!",
    url: "url",
    img: "/assets/img11.jpg",
    category: "Web, iOS & Android App",
  },
];
